// Generated by scripts/pack-gallery.mjs — do not edit.
// Placeholder until the first pack is built: an empty key means no pack exists,
// and the gallery falls back to the plain images in data/gallery.js.
export const GALLERY_KEY = "";
