// Generated by scripts/pack-frames.mjs — do not edit.
// Kept out of the manifest on purpose: manifest fields become props and are
// serialized into the page HTML in the clear, whereas this lands in a JS chunk.
export const MASK_KEY = "PMYItl6FjBo9ZXD4UcDh4mIaWz9OY2JwV9O+W2ht8rI=";
